name: UI Automation Tests

permissions:
  contents: write  # Changed from read to write
  pages: write
  id-token: write

env:
  SITE_ARTIFACT: "github-pages"
  # Add debug logging for GitHub Actions
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'
  pull_request:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'
  workflow_dispatch:

jobs:
  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UI Testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper GitHub Pages deployment

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
          cache: 'npm'
          cache-dependency-path: './UI Testing/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Setup Display
        run: |
          sudo apt-get install -y xvfb
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Cucumber Tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx cucumber-js --retry 1
        env:
          CI: true
          PLAYWRIGHT_HEADLESS: true
          DEBUG: pw:api  # Add Playwright debug logging

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: |
            ./UI Testing/allure-report/
            ./UI Testing/test-results/
          retention-days: 14

      # Switch back to using peaceiris/actions-gh-pages for deployment
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./UI Testing/allure-report
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Allure report to GitHub Pages'
