name: UI Automation Tests

on:
  push:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'
  pull_request:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UI Testing

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
          cache: 'npm'
          cache-dependency-path: './UI Testing/package-lock.json'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests in headless mode
      - name: Run UI Tests
        run: |
          npx cucumber-js --headless
        env:
          PLAYWRIGHT_HEADLESS: 'true'

      # Optional: Save artifacts or test results
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./UI Testing/test-results/
