name: UI Automation Tests

on:
  push:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'  # Trigger only on changes to the UI Testing directory
  pull_request:
    branches: [main, master, development]
    paths:
      - 'UI Testing/**'
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UI Testing  # Set the default working directory

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
          cache: 'npm'
          cache-dependency-path: './UI Testing/package-lock.json'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm ci

      # Step 4: Install Playwright browsers with required dependencies
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      # Step 5: Run Cucumber.js tests
      - name: Run Cucumber Tests
        run: npx cucumber-js
        env:
          CI: true

      # Step 6: Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      # Step 7: Upload test results as an artifact
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: |
            ./UI Testing/allure-report/
            ./UI Testing/test-results/
          retention-days: 14

      # Step 8: Deploy the report to GitHub Pages
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./UI Testing/allure-report
          destination_dir: ui-test-report
